### ISSUE TITLE
Installing from npm

### ISSUE THREAD

**Issue by denisemauldin** [dasmoth/dalliance#237]
Attempting to install from npm following the README.md throws an error.

```
npm install dalliance
cd node_modules/dalliance
npm install -g gulp
npm install
gulp
```

```
Error: Cannot find module './node_modules/browserify/lib/builtins.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Transform.transform [as _transform] (node_modules/dalliance/node_modules/gulp-browserify/index.js:81:22)
    at Transform._read (node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (node_modules/dalliance/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (node_modules/dalliance/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (node_modules/dalliance/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (node_modules/dalliance/node_modules/gulp-browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11
```

**Comment by dasmoth** [comment]
You shouldn't need to run this when installing from npm.  However, the npm package is quite old (and was uploaded by a third party).  I'm hoping it'll be possible to update it in the coming weeks.

In the mean time, if you're trying to compile yourself, right now I'd suggest starting with a Git checkout of the master branch.
